Dockerfile
backend/.gitignore
backend/backend/settings.py
backend/backend/urls.py
backend/frontend/admin.py
backend/frontend/apps.py
backend/frontend/models.py
backend/frontend/templates/frontend/index.html
backend/frontend/tests.py
backend/frontend/urls.py
backend/frontend/views.py
frontend/vite.config.js

Still needs to be completed with the django portion

feat: Dockerfile wrapper for application

---

.github/workflows/deploy.yaml
.github/workflows/version.yaml
Dockerfile
backend/backend/settings.py
frontend/package.json

Not tested yet. Needs the dockerize branch to be merged first

ci: Basic build and deploy to cloud run

---

backend/.gitignore
backend/backend/settings.py

Backend setup

---

.github/workflows/deploy.yaml
Dockerfile

fix: Added DJANG_SECRET env var

---

backend/requirements.txt

fix: Installed python-dotenv

---

frontend/src/main.jsx
frontend/src/pages/Login.css
frontend/src/pages/Login.jsx

creating login page on frontend side

login page on frontend side

---

frontend/package-lock.json
frontend/package.json
frontend/vite.config.js

This should fix the failing build

fix: Installed MUI and removed SWC

---

frontend/src/pages/Login.jsx

This will fix the username and password 50px border radius

fix: Fixed MUI CSS

---

.github/AUTOMATIC_ISSUE_TEMPLATE.md
.github/workflows/deploy.yaml
integration_tests/health.sh

ci: Added integration tests to build and deploy pipeline

---

.github/workflows/test.yaml
backend/.gitignore
backend/apis/models.py
backend/apis/tests.py
backend/apis/tests/tests_auth_views.py
backend/apis/tests/tests_db.py
backend/apis/tests/tests_manager_views.py
backend/apis/urls.py
backend/apis/views.py
backend/apis/views/auth_views.py
backend/apis/views/manager_views.py
backend/backend/settings.py
backend/backend/urls.py
backend/requirements.txt
backend/utils.py
frontend/package-lock.json
frontend/package.json

Added  utilts.py to access models created for #38. Closes #38 
To Do:
Work on #41 , #9

Mongo connection + Auth API endpoint + Add/Delete Manager endpoint

---

frontend/src/main.jsx
frontend/src/routes.jsx

adding routes to make it easier to navigate using hooks

adding routes

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/api.js

feat: Dynamic API object

---

.github/workflows/deploy.yaml
Dockerfile
backend/chatgpt.py
backend/requirements.txt

Closes #56
Pulls the `AI_KEY` env var from the actions secret. Will have to be set locally to use locally. Won't error if key isn't set unless function is called.

feat: Added generic function to query chatgpt

---

frontend/src/pages/Login.jsx

adding simple login functionality

---

frontend/src/pages/Job.css
frontend/src/pages/Job.jsx
frontend/src/pages/JobDescription.css
frontend/src/pages/JobDescription.jsx
frontend/src/pages/JobListings.css
frontend/src/pages/JobListings.jsx

adding jobListing frontend stuff

---

.github/workflows/deploy.yaml
Dockerfile
integration_tests/login.sh

fix: Added mongo connection string to dockerfile and deployment CI

---

frontend/src/main.jsx
frontend/src/pages/Job.css
frontend/src/pages/Job.jsx
frontend/src/pages/JobDescription.css
frontend/src/pages/JobDescription.jsx
frontend/src/pages/JobListings.css
frontend/src/pages/JobListings.jsx
frontend/src/pages/Login.css

Cleaned up some of the UI for the job postings page.

Updated UI for Job Postings

---

integration_tests/health.sh

Commenting it out to re-run tests

Commenting out /admin/login test

---

Dockerfile

Updated Mongo Connection String

---

backend/backend/settings.py
backend/requirements.txt

fix: Allow cors in local mode

---

backend/apis/urls.py
backend/apis/views/jobListings_views.py
backend/apis/views/job_views.py

Clears up everything for job listing backend
Finishes off #39

Job backend

---

frontend/src/pages/JobListings.jsx

Added implementation for searching job listings by job title, company, and location.

Frontend search

---

backend/apis/models.py
backend/apis/urls.py
backend/apis/views/jobApplication_views.py
backend/apis/views/job_views.py
backend/apis/views/updateApplication_views.py
backend/backend/settings.py

adding applications API

---

backend/backend/urls.py

fix: Added jobListed to backend URL list

---

frontend/src/pages/ApplicantTable.jsx

feat: Reject all remaining button

---

frontend/src/pages/JobListings.jsx

Added a user menu.
Added a "delete my account" button in the user menu under the user's symbol.

114 delete my account

---

frontend/src/pages/Login.jsx

feat: Admin users are redirected properally

---

frontend/src/pages/SignUp.jsx

Fixed some uncaught issues with SignUp page

Fixed issues with SignUp

---

backend/backend/urls.py
frontend/src/routes.jsx

Removed unused /addJob, /applyJob routes. Added the /jobs, /createJob routes to the backend router

Edited backend & frontend routes

---

backend/apis/models.py
backend/apis/views/jobListings_views.py
backend/apis/views/job_views.py
frontend/src/pages/CreateJob.jsx
frontend/src/pages/JobDescription.css
frontend/src/pages/JobDescription.jsx

adding job id and job start date
